project:
  type: website
  output-dir: docs

website:
  title: "Coding and Curiosity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Jacob
      - href: resume.qmd
        text: Resume
    right:
      - href: https://github.com/JacobBrown6908
        text: "<i class='fab fa-github'></i> GitHub"
      - href: https://www.linkedin.com/in/jacob-brown-9230582aa/
        text: "<i class='fab fa-linkedin'></i> LinkedIn"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



