project:
  type: website
  output-dir: docs

website:
  title: "Coding and Curiosity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Jacob
      - href: resume.qmd
        text: Resume
    right:
      - href: "https://www.linkedin.com/in/jacob-brown-9230582aa/"
        icon: LinkedIn
      - href: "https://github.com/JacobBrown6908"
        icon: github


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



