project:
  type: website

website:
  title: "Coding and Curiosity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Jacob
      - href: resume.pdf
        text: Resume
        target: _blank
      - href: resume.qmd
        text: Resume test

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



